### ISSUE TITLE
android端末用のpush通知を実装しておくれ

### ISSUE THREAD

**Issue by lastcat** [OpenYo/OpenYo#2]
GoogleDeveloperConsole(https://console.developers.google.com/ )でprojectを作成して、そのprojectNumberとapi_keyを教えてもらいたいです。あと、DBのカラムに端末idを登録するapiを増やしてもらいたいです。サーバ側からのpush通知は、
curl --header "Authorization: key=＜API KEY＞" --header Content-Type:"application/json" https://android.googleapis.com/gcm/send -d "{\"registration_ids\":[\"＜RegistrationID＞\"],\"data\":{\"message\":\"Hello\"}}"
みたいな感じでjson投げてもらえば可能です。以下のページが詳しいです。
http://dev.classmethod.jp/smartphone/android/gcm/

**Comment by nna774** [comment]
@lastcat project 作成してapi_key 取りました。通知される側からはprojectNumber だけが必要で、api_key は必要無い感じに思うのですがどうですか？
projectNumber は`890988864794` です。api_key はここには書けないですが、テスト等で必要ならば別の手段で送ります。
RegistrationID を設定するapi は用意します。

**Comment by nna774** [comment]
これ、projectNumber とapi_key を用意してもらって教えてもらったほうがいいのでは って気もする(projectNumber はアプリ作者の持ち物であるほうが自然？)。

**Comment by lastcat** [comment]
うーん各サービス（クローン達）がそれぞれのprojectNumberを持っている方が自然だと思うんだけど、どうだろ。別にそっち（androidアプリがprojectNumberを持つ）でもいいとは思うんだけど。

**Comment by lastcat** [comment]
と思ったけど、やっぱりクライアント側で持つことにします（ライブラリ化したいと考えてるので、projectNumberはアプリ側がもっといたほうがいいんだった）。APIKEYはメールで送ればいいですか

**Comment by nna774** [comment]
どうしたほうがいいかなー って文章打ちかけてたけど, それならお願いします～
メール, あんまり良くないかもですけど, まぁ大丈夫でしょう. お願いします.

**Comment by lastcat** [comment]
OKOK~

**Comment by nna774** [comment]
https://github.com/nna774/OpenYo/commit/18b759f334e067d05c29cc16f6389df04914f7bc で追加した、`/config/add_gcm_id/` で良いですか？ > regID を登録するapi
username, password, projectNumber, RegistrationID を投げてもらって、そこへの通知を有効にする予定です。

**Comment by lastcat** [comment]
おお、じゃあ一回試してみようかな……ちなみにサーバ側からpushできる準備は整ってますか？

**Comment by nna774** [comment]
まだ実装中です…… (`/config/add_gcm_id/` も含め。)

**Comment by lastcat** [comment]
naruhodo……とりあえず/config/add_gcm_id/ができたら一回連携テストしてみたいので教えてください。

**Comment by nna774** [comment]
とりあえず実装しました。
まだどっかバグってるかもですが、とりあえずおねがいします。

**Comment by nna774** [comment]
[GCM](https://github.com/nna774/OpenYo/tree/gcm) に通知してくれそうなものを書きました。私の環境ではテストしようがないので、お願いします。
今[`OpenYo.nna774.net`](https://OpenYo.nna774.net) はこのGCM ブランチが走っています(本番環境でテストするな)。

**Comment by nna774** [comment]
とりあえず動くようになりました。
